
# CREANDO TUPLAS CON TUPLE()
tupla = tuple(["dato1", "dato2"])

# CREANDO UNA TUPLA SIN PARENTESIS DE MULTIPLES DATOS
tupla = "dato1","dato2"

# CREANDO UNA TUPLA SIN PARENTESIS DE UN SOLO DATO
tupla = "dato1",