
# CREANDO UNA LISTA CON list()
lista = list(["Soy de san lorenzo, peronismo de mierda"])

# DEVUELVE LA CANTIDAD DE ELEMENTOS DE LA LISTA
cantidad_de_elementos = len(lista)

# AGREGANDO UN ELEMENTO A LA LISTA
lista.append("JAJAJAJAJA")

# AGREGANDO UN ELEMENTO A LA LISTA EN UN INIDICE ESPECIFICO
lista.insert(2,"TOMA MAMA")

# AGREGANDO VARIOS ELEMENTOS A LA LISTA
lista.extend([False,2030])

# ELIMINANDO UN ELEMENTO DE LA LISTA POR SU INDICE
lista.pop(0) # -1 PARA ELMINAR EL ULTIMO ELEMENTO, - 2 ANTE ULTIMO, SUCESIVAMENTE

# REMOVIENDO UN ELEMENTO DE LA LISTA POR SU VALOR
lista.remove("TOMA MAMA")

# ORDENA LOS ELEMENTOS DE FORMA ASCENDENTE
# SI USAMOS EL REVERSE=TRUE LO ORDENA DE FORMA DESCENDENTE
#lista.sort()

# INVIERTE LOS ELEMENTOS DE UNA LISTA
lista.reverse()




# ELIMINANDO TODOS LOS ELEMENTOS DE LA LISTA




print(lista)